// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        (unknown)
// source: github.com/kralicky/protols/sdk/codegen/generators/golang/grpc/grpc.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GeneratorOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Equivalent to the 'require_unimplemented_servers' flag. Defaults to false.
	RequireUnimplemented *bool `protobuf:"varint,1,opt,name=require_unimplemented,json=requireUnimplemented,proto3,oneof" json:"require_unimplemented,omitempty"`
	// Equivalent to the 'use_generic_streams_experimental' flag. Defaults to true.
	UseGenericStreams *bool `protobuf:"varint,2,opt,name=use_generic_streams,json=useGenericStreams,proto3,oneof" json:"use_generic_streams,omitempty"`
}

func (x *GeneratorOptions) Reset() {
	*x = GeneratorOptions{}
	mi := &file_github_com_kralicky_protols_sdk_codegen_generators_golang_grpc_grpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeneratorOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneratorOptions) ProtoMessage() {}

func (x *GeneratorOptions) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_kralicky_protols_sdk_codegen_generators_golang_grpc_grpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneratorOptions.ProtoReflect.Descriptor instead.
func (*GeneratorOptions) Descriptor() ([]byte, []int) {
	return file_github_com_kralicky_protols_sdk_codegen_generators_golang_grpc_grpc_proto_rawDescGZIP(), []int{0}
}

func (x *GeneratorOptions) GetRequireUnimplemented() bool {
	if x != nil && x.RequireUnimplemented != nil {
		return *x.RequireUnimplemented
	}
	return false
}

func (x *GeneratorOptions) GetUseGenericStreams() bool {
	if x != nil && x.UseGenericStreams != nil {
		return *x.UseGenericStreams
	}
	return false
}

var file_github_com_kralicky_protols_sdk_codegen_generators_golang_grpc_grpc_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FileOptions)(nil),
		ExtensionType: (*GeneratorOptions)(nil),
		Field:         25400,
		Name:          "grpc.generator",
		Tag:           "bytes,25400,opt,name=generator",
		Filename:      "github.com/kralicky/protols/sdk/codegen/generators/golang/grpc/grpc.proto",
	},
}

// Extension fields to descriptorpb.FileOptions.
var (
	// optional grpc.GeneratorOptions generator = 25400;
	E_Generator = &file_github_com_kralicky_protols_sdk_codegen_generators_golang_grpc_grpc_proto_extTypes[0]
)

var File_github_com_kralicky_protols_sdk_codegen_generators_golang_grpc_grpc_proto protoreflect.FileDescriptor

var file_github_com_kralicky_protols_sdk_codegen_generators_golang_grpc_grpc_proto_rawDesc = []byte{
	0x0a, 0x49, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x72, 0x61,
	0x6c, 0x69, 0x63, 0x6b, 0x79, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6c, 0x73, 0x2f, 0x73, 0x64,
	0x6b, 0x2f, 0x63, 0x6f, 0x64, 0x65, 0x67, 0x65, 0x6e, 0x2f, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61,
	0x74, 0x6f, 0x72, 0x73, 0x2f, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2f, 0x67, 0x72, 0x70, 0x63,
	0x2f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x67, 0x72, 0x70,
	0x63, 0x1a, 0x20, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0xb3, 0x01, 0x0a, 0x10, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x6f,
	0x72, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x38, 0x0a, 0x15, 0x72, 0x65, 0x71, 0x75,
	0x69, 0x72, 0x65, 0x5f, 0x75, 0x6e, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x65,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x14, 0x72, 0x65, 0x71, 0x75, 0x69,
	0x72, 0x65, 0x55, 0x6e, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x65, 0x64, 0x88,
	0x01, 0x01, 0x12, 0x33, 0x0a, 0x13, 0x75, 0x73, 0x65, 0x5f, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x69,
	0x63, 0x5f, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x48,
	0x01, 0x52, 0x11, 0x75, 0x73, 0x65, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x69, 0x63, 0x53, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x73, 0x88, 0x01, 0x01, 0x42, 0x18, 0x0a, 0x16, 0x5f, 0x72, 0x65, 0x71, 0x75,
	0x69, 0x72, 0x65, 0x5f, 0x75, 0x6e, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x65,
	0x64, 0x42, 0x16, 0x0a, 0x14, 0x5f, 0x75, 0x73, 0x65, 0x5f, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x69,
	0x63, 0x5f, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x73, 0x3a, 0x54, 0x0a, 0x09, 0x67, 0x65, 0x6e,
	0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x1c, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x4f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x18, 0xb8, 0xc6, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x67,
	0x72, 0x70, 0x63, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x4f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x52, 0x09, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x42,
	0x40, 0x5a, 0x3e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x72,
	0x61, 0x6c, 0x69, 0x63, 0x6b, 0x79, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6c, 0x73, 0x2f, 0x73,
	0x64, 0x6b, 0x2f, 0x63, 0x6f, 0x64, 0x65, 0x67, 0x65, 0x6e, 0x2f, 0x67, 0x65, 0x6e, 0x65, 0x72,
	0x61, 0x74, 0x6f, 0x72, 0x73, 0x2f, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2f, 0x67, 0x72, 0x70,
	0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_github_com_kralicky_protols_sdk_codegen_generators_golang_grpc_grpc_proto_rawDescOnce sync.Once
	file_github_com_kralicky_protols_sdk_codegen_generators_golang_grpc_grpc_proto_rawDescData = file_github_com_kralicky_protols_sdk_codegen_generators_golang_grpc_grpc_proto_rawDesc
)

func file_github_com_kralicky_protols_sdk_codegen_generators_golang_grpc_grpc_proto_rawDescGZIP() []byte {
	file_github_com_kralicky_protols_sdk_codegen_generators_golang_grpc_grpc_proto_rawDescOnce.Do(func() {
		file_github_com_kralicky_protols_sdk_codegen_generators_golang_grpc_grpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_github_com_kralicky_protols_sdk_codegen_generators_golang_grpc_grpc_proto_rawDescData)
	})
	return file_github_com_kralicky_protols_sdk_codegen_generators_golang_grpc_grpc_proto_rawDescData
}

var file_github_com_kralicky_protols_sdk_codegen_generators_golang_grpc_grpc_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_github_com_kralicky_protols_sdk_codegen_generators_golang_grpc_grpc_proto_goTypes = []any{
	(*GeneratorOptions)(nil),         // 0: grpc.GeneratorOptions
	(*descriptorpb.FileOptions)(nil), // 1: google.protobuf.FileOptions
}
var file_github_com_kralicky_protols_sdk_codegen_generators_golang_grpc_grpc_proto_depIdxs = []int32{
	1, // 0: grpc.generator:extendee -> google.protobuf.FileOptions
	0, // 1: grpc.generator:type_name -> grpc.GeneratorOptions
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	1, // [1:2] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_github_com_kralicky_protols_sdk_codegen_generators_golang_grpc_grpc_proto_init() }
func file_github_com_kralicky_protols_sdk_codegen_generators_golang_grpc_grpc_proto_init() {
	if File_github_com_kralicky_protols_sdk_codegen_generators_golang_grpc_grpc_proto != nil {
		return
	}
	file_github_com_kralicky_protols_sdk_codegen_generators_golang_grpc_grpc_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_github_com_kralicky_protols_sdk_codegen_generators_golang_grpc_grpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_github_com_kralicky_protols_sdk_codegen_generators_golang_grpc_grpc_proto_goTypes,
		DependencyIndexes: file_github_com_kralicky_protols_sdk_codegen_generators_golang_grpc_grpc_proto_depIdxs,
		MessageInfos:      file_github_com_kralicky_protols_sdk_codegen_generators_golang_grpc_grpc_proto_msgTypes,
		ExtensionInfos:    file_github_com_kralicky_protols_sdk_codegen_generators_golang_grpc_grpc_proto_extTypes,
	}.Build()
	File_github_com_kralicky_protols_sdk_codegen_generators_golang_grpc_grpc_proto = out.File
	file_github_com_kralicky_protols_sdk_codegen_generators_golang_grpc_grpc_proto_rawDesc = nil
	file_github_com_kralicky_protols_sdk_codegen_generators_golang_grpc_grpc_proto_goTypes = nil
	file_github_com_kralicky_protols_sdk_codegen_generators_golang_grpc_grpc_proto_depIdxs = nil
}
