// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: github.com/kralicky/protols/sdk/codegen/generators/golang/grpc/grpc.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GeneratorOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Equivalent to the 'require_unimplemented_servers' flag. Defaults to false.
	RequireUnimplemented *bool `protobuf:"varint,1,opt,name=require_unimplemented,json=requireUnimplemented,proto3,oneof" json:"require_unimplemented,omitempty"`
	// Equivalent to the 'use_generic_streams_experimental' flag. Defaults to true.
	UseGenericStreams *bool `protobuf:"varint,2,opt,name=use_generic_streams,json=useGenericStreams,proto3,oneof" json:"use_generic_streams,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GeneratorOptions) Reset() {
	*x = GeneratorOptions{}
	mi := &file_github_com_kralicky_protols_sdk_codegen_generators_golang_grpc_grpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeneratorOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneratorOptions) ProtoMessage() {}

func (x *GeneratorOptions) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_kralicky_protols_sdk_codegen_generators_golang_grpc_grpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneratorOptions.ProtoReflect.Descriptor instead.
func (*GeneratorOptions) Descriptor() ([]byte, []int) {
	return file_github_com_kralicky_protols_sdk_codegen_generators_golang_grpc_grpc_proto_rawDescGZIP(), []int{0}
}

func (x *GeneratorOptions) GetRequireUnimplemented() bool {
	if x != nil && x.RequireUnimplemented != nil {
		return *x.RequireUnimplemented
	}
	return false
}

func (x *GeneratorOptions) GetUseGenericStreams() bool {
	if x != nil && x.UseGenericStreams != nil {
		return *x.UseGenericStreams
	}
	return false
}

var file_github_com_kralicky_protols_sdk_codegen_generators_golang_grpc_grpc_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FileOptions)(nil),
		ExtensionType: (*GeneratorOptions)(nil),
		Field:         25400,
		Name:          "grpc.generator",
		Tag:           "bytes,25400,opt,name=generator",
		Filename:      "github.com/kralicky/protols/sdk/codegen/generators/golang/grpc/grpc.proto",
	},
}

// Extension fields to descriptorpb.FileOptions.
var (
	// optional grpc.GeneratorOptions generator = 25400;
	E_Generator = &file_github_com_kralicky_protols_sdk_codegen_generators_golang_grpc_grpc_proto_extTypes[0]
)

var File_github_com_kralicky_protols_sdk_codegen_generators_golang_grpc_grpc_proto protoreflect.FileDescriptor

const file_github_com_kralicky_protols_sdk_codegen_generators_golang_grpc_grpc_proto_rawDesc = "" +
	"\n" +
	"Igithub.com/kralicky/protols/sdk/codegen/generators/golang/grpc/grpc.proto\x12\x04grpc\x1a google/protobuf/descriptor.proto\"\xb3\x01\n" +
	"\x10GeneratorOptions\x128\n" +
	"\x15require_unimplemented\x18\x01 \x01(\bH\x00R\x14requireUnimplemented\x88\x01\x01\x123\n" +
	"\x13use_generic_streams\x18\x02 \x01(\bH\x01R\x11useGenericStreams\x88\x01\x01B\x18\n" +
	"\x16_require_unimplementedB\x16\n" +
	"\x14_use_generic_streams:T\n" +
	"\tgenerator\x12\x1c.google.protobuf.FileOptions\x18\xb8\xc6\x01 \x01(\v2\x16.grpc.GeneratorOptionsR\tgeneratorB@Z>github.com/kralicky/protols/sdk/codegen/generators/golang/grpcb\x06proto3"

var (
	file_github_com_kralicky_protols_sdk_codegen_generators_golang_grpc_grpc_proto_rawDescOnce sync.Once
	file_github_com_kralicky_protols_sdk_codegen_generators_golang_grpc_grpc_proto_rawDescData []byte
)

func file_github_com_kralicky_protols_sdk_codegen_generators_golang_grpc_grpc_proto_rawDescGZIP() []byte {
	file_github_com_kralicky_protols_sdk_codegen_generators_golang_grpc_grpc_proto_rawDescOnce.Do(func() {
		file_github_com_kralicky_protols_sdk_codegen_generators_golang_grpc_grpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_com_kralicky_protols_sdk_codegen_generators_golang_grpc_grpc_proto_rawDesc), len(file_github_com_kralicky_protols_sdk_codegen_generators_golang_grpc_grpc_proto_rawDesc)))
	})
	return file_github_com_kralicky_protols_sdk_codegen_generators_golang_grpc_grpc_proto_rawDescData
}

var file_github_com_kralicky_protols_sdk_codegen_generators_golang_grpc_grpc_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_github_com_kralicky_protols_sdk_codegen_generators_golang_grpc_grpc_proto_goTypes = []any{
	(*GeneratorOptions)(nil),         // 0: grpc.GeneratorOptions
	(*descriptorpb.FileOptions)(nil), // 1: google.protobuf.FileOptions
}
var file_github_com_kralicky_protols_sdk_codegen_generators_golang_grpc_grpc_proto_depIdxs = []int32{
	1, // 0: grpc.generator:extendee -> google.protobuf.FileOptions
	0, // 1: grpc.generator:type_name -> grpc.GeneratorOptions
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	1, // [1:2] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_github_com_kralicky_protols_sdk_codegen_generators_golang_grpc_grpc_proto_init() }
func file_github_com_kralicky_protols_sdk_codegen_generators_golang_grpc_grpc_proto_init() {
	if File_github_com_kralicky_protols_sdk_codegen_generators_golang_grpc_grpc_proto != nil {
		return
	}
	file_github_com_kralicky_protols_sdk_codegen_generators_golang_grpc_grpc_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_kralicky_protols_sdk_codegen_generators_golang_grpc_grpc_proto_rawDesc), len(file_github_com_kralicky_protols_sdk_codegen_generators_golang_grpc_grpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_github_com_kralicky_protols_sdk_codegen_generators_golang_grpc_grpc_proto_goTypes,
		DependencyIndexes: file_github_com_kralicky_protols_sdk_codegen_generators_golang_grpc_grpc_proto_depIdxs,
		MessageInfos:      file_github_com_kralicky_protols_sdk_codegen_generators_golang_grpc_grpc_proto_msgTypes,
		ExtensionInfos:    file_github_com_kralicky_protols_sdk_codegen_generators_golang_grpc_grpc_proto_extTypes,
	}.Build()
	File_github_com_kralicky_protols_sdk_codegen_generators_golang_grpc_grpc_proto = out.File
	file_github_com_kralicky_protols_sdk_codegen_generators_golang_grpc_grpc_proto_goTypes = nil
	file_github_com_kralicky_protols_sdk_codegen_generators_golang_grpc_grpc_proto_depIdxs = nil
}
